[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

python_files = "apis.py"
python_classes = "Test"
python_functions = "chain*"

md_report = true
md_report_verbose = 1
md_report_color = "auto"
