name: Test RPC and LCD endpoints

on:
  workflow_dispatch:

jobs:
  test-endpoints:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r _tests/requirements.txt

    - name: Run tests
      run: |
        pytest -n auto _tests
